name: loyoo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  uuid: ^4.3.3
  dio: ^5.4.0
  audio_session: ^0.1.18
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.2.0
  logger: ^2.0.2+1
  http: ^1.2.0
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.12
  intl: ^0.18.0
  sqflite: ^2.3.2
  sqflite_common: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/characters.json
    - assets/images/
    - assets/1.mp3
    - assets/2.mp3
    - assets/3.mp3
    - assets/4.mp3
    - assets/5.mp3
